#!/usr/bin/env python3
"""Generate the 8 FROZEN production-octant configs (paper campaign, 2026-07-27).

One simulation volume (seed 12345), eight observer corners = full sky.
Octant name convention (matches the original campaign): octZYX bits, bit=1 means
observer at +boxsize/2 on that axis, bit=0 means -boxsize/2.
  oct000 -> (cenx,ceny,cenz) = (-2618,-2618,-2618); oct100 -> (-2618,-2618,+2618).

Frozen choices (docs/paper_plan.md §3.1):
  N=6144, box = 5236 Mpc/h (= 7700 Mpc, the factor-h-corrected Websky box),
  ntile=16, n=414, nbuff=16, cellsize 0.85221 Mpc/h,
  coarse_factor=32 (velocity-coherence requirement, KSZ_COMPOSITE_2026-07-19.md),
  z_max=4.5 (matches the released Websky late-time maps; removes the +10%
  low-ell kSZ residual the z<4.6 runs carried), 2LPT, ioutshear=1,
  finecell filter bank.

The generated configs are COMMITTED — regenerate only to change the frozen set.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OBS = 2618.0  # |observer| per axis = boxsize_full/2 (5236/2), Mpc/h

TEMPLATE = """# FROZEN production config — paper campaign 2026-07-27 (docs/paper_plan.md).
# Octant {oct}: observer at ({cenx}, {ceny}, {cenz}) Mpc/h (centered coords).
# Generated by production/generate_configs.py — do not hand-edit.
#
# Geometry: ntile=16, n=414, nbuff=16; nsub=382; N=6144;
# cellsize = 5236/6144 = 0.85221 Mpc/h (= Websky's 0.852); box = 5236 Mpc/h = 7700 Mpc.

[cosmology]
Om   = 0.31
OB   = 0.049
OL   = 0.69
h    = 0.68

[grid]
n       = 414
boxsize = 352.8164
nbuff   = 16
cenx    = {cenx}
ceny    = {ceny}
cenz    = {cenz}

[run]
z_out     = 0.0
z_max     = 4.5
ievol     = 1
ilpt      = 2
ioutshear = 1
wsmooth   = 1
rmax2rs   = 0.0
NonGauss  = 0
fNL       = 0.0
seed      = 12345
ntile     = 16
coarse_factor = 32
generate_table = false

[files]
pk         = "validation/websky_6144/data/pk_websky.dat"
filterbank = "validation/websky_6144/data/filters_websky_finecell.dat"
homeltab   = "validation/websky_6144/data/HomelTab_websky.dat"
output     = "catalog_websky_6144_prod_oct{oct}.pksc"

[output]
format = "pksc"
path   = "/home/yguan/projects/aip-aspuru-ab/yguan/websky"
"""

for z in "01":
    for y in "01":
        for x in "01":
            oct_ = z + y + x   # octZYX
            cen = {
                "cenx": OBS if x == "1" else -OBS,
                "ceny": OBS if y == "1" else -OBS,
                "cenz": OBS if z == "1" else -OBS,
            }
            path = os.path.join(HERE, f"config_prod_oct{oct_}.toml")
            with open(path, "w") as f:
                f.write(TEMPLATE.format(oct=oct_, **cen))
            print(f"wrote {path}  obs=({cen['cenx']:+.0f},{cen['ceny']:+.0f},{cen['cenz']:+.0f})")
